### PR TITLE
Allow implementations of the (de)serialization constructor not using the streaming context.

### PR DESCRIPTION
**Pull request by Corniel**

### CODE REVIEW

**Comment by tvsonar** [comment]
@Corniel Don't worry about the failing test. I'm gonna take care of it. (I'll rework a bit this PR to use our `KnownType` class for type checking.)

**Comment by tvsonar** [comment]
Just for the record, this PR was based on https://github.com/SonarSource-VisualStudio/sonaranalyzer-dotnet/pull/1034, but the discussion over there is still valid.

**Comment by tvsonar** [comment]
@Corniel Thanks for your contribution again. I pushed these changes to master with https://github.com/SonarSource-VisualStudio/sonaranalyzer-dotnet/commit/a005577da03c42470e0e47b7dd2c5d5c44a10161.

**Comment by Corniel** [comment]
The thing was NOTcompliant v.s. NONcompliant. Me bad. ;)

**Pull request closed without merging**
